name: SDITAA
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - beautifulsoup4
  - nptyping
  - seaborn
  - jupyterlab
  - cartopy
  - pip
  - pip:
    - mypy
    - sgp4
